### ISSUE TITLE
Composer install fails with 'Could not open input file: app/console'

### ISSUE THREAD

**Issue by JeanFred** [wikimedia-france/Lingua-Libre#1]
Hi,

`composer install` fails for me with

```
Could not open input file: app/console
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception


  [RuntimeException]                                                         
  An error occurred when executing the "'cache:clear --no-warmup'" command:  
  Could not open input file: app/console                                     
```

Looking around this seems to be a fairly classic issue when using Symfony, would you know what’s wrong here?

Thanks!

**Comment by zmoostik** [comment]
Hi!

Yes, it is a classic non-blocking bug...

"app/console" no more exists since Symfony 3 (yet it is bin/console)

Regards,
Nicolas

**Comment by hugolpz** [comment]
@zmoostik could you close this issue if needed to be.
Hi Zmoostik :D

**Comment by JeanFred** [comment]
Closing this, I tried again the other day and it passed :)

**Comment by tshrinivasan** [comment]
How to solve this issue?

I can not come out of this issue and can not install the application.

**Comment by rivelbab** [comment]
thanks Nicolas
