### ISSUE TITLE
Add Odia language in dropdown list

### ISSUE THREAD

**Issue by psubhashish** [wikimedia-france/Lingua-Libre#12]
Request moved to #18.

----

Hi, there is something which needs immediate intervention, of course, depending on how much time you have:

- [x] [Odia language](https://en.wikipedia.org/wiki/Odia_language) : or

Without that I cannot contribute in any way. I'am actively involve with Wikimedia India to preserve this language.

**Comment by 0x010C** [comment]
{{done}} 🐈

**Comment by psubhashish** [comment]
@hugolpz  I tried multiple times to add a profile in my language and record. But inside the "Recording Studio" it only shows a language (Occitan) that I don't speak. I tried to add my language again but it just would not show my language inside the recording studio.

Sharing a [screencast](https://commons.wikimedia.org/wiki/File:Issue_in_recording_with_LinguaLibre.gif) below:
![lingualibre-issue-with-recording](https://cloud.githubusercontent.com/assets/1258090/25401087/55493426-2a12-11e7-87de-384aecb50507.gif)

**Comment by hugolpz** [comment]
I think @0x010C needs to push the code to github / the website.
We welcome you to contribute in Occitan :yum::bowtie:

**Comment by hugolpz** [comment]
I'am meeting up with @0x010C and @xenophon75 today so I can understand better their workflow. Will see :)

**Comment by hugolpz** [comment]
@psubhashish : The drop down menu works for me. But the recording didn't (I'am have no external microphone this week).
2) Tutorials and English UI planned in coming one or two months. Aka : when the respective people get a truly free weekend.

**Comment by hugolpz** [comment]
I'am with @tshrinivasan ! :D

**Comment by psubhashish** [comment]
Wow, hi to both of you. I wish I can contribute to Occitan but I don't know a bit. BTW I tried to record again but could not even record a word in Odia. It still shows Occitan.

**Comment by hugolpz** [comment]
We found out today that we were editing and adding up languages to the wrong table.
Will fix this today.
