### ISSUE TITLE
Add settings "silence-time-for-cut" to support recording of paragraphs

### ISSUE THREAD

**Issue by tshrinivasan** [wikimedia-france/Lingua-Libre#17]
Recording words is fine.

It will be nice if recording paragraphs is possible. if so, we can create audio books easily.
![recording-paragraphs-librelingue](https://cloud.githubusercontent.com/assets/1268536/26261847/6d3bade8-3cf0-11e7-840a-c1d3cf762f0d.jpg)

**Comment by hugolpz** [comment]
@tshrinivasan tested paragraph recording in front of me, but the "silence-time-for-cut" thresold is too short, so the recording was cut after the `paragraph-#2-end-of-sentence-#1-(first-dot)`. It need to allow longer silence before cutting the recording.
