### ISSUE TITLE
Add requested languages into dropdown list (Vienna Hackathon)

### ISSUE THREAD

**Issue by bodhisattwawiki** [wikimedia-france/Lingua-Libre#18]
Add major Indian languages in dropdown list of Lingua Libre.

- [x] [Tamil](https://en.wikipedia.org/wiki/Tamil_language) : ta | tam
- [x] [Bengali](https://en.wikipedia.org/wiki/Bengali_language) : bn | ben
- [x] [Western Punjabi](https://en.wikipedia.org/wiki/Western_Punjabi) : lah | lah
- [x] [Urdu](https://en.wikipedia.org/wiki/Urdu) : ur | urd
- [x] [Marathi](https://en.wikipedia.org/wiki/Marathi_language) : mr | mar
- [x] [Hebrew](https://en.wikipedia.org/wiki/Hebrew_language) : he | heb
- [x] [Telugu](https://en.wikipedia.org/wiki/Telugu_language) : te | tel
- [x] [Odia language](https://en.wikipedia.org/wiki/Odia_language) : or | ory
- [x] [Chinese Mandarin language](https://en.wikipedia.org/wiki/Mandarin_Chinese) : <no 639-2> | cmn

| Language | Language | Language |
| ---- | ---- | ---- |
| ![screenshot from 2017-05-19 22-17-48](https://cloud.githubusercontent.com/assets/1420189/26265329/09658c94-3ce1-11e7-9fd6-2aded1fdf5b4.png) | ![screenshot from 2017-05-19 22-21-22](https://cloud.githubusercontent.com/assets/1420189/26265728/8f190c20-3ce2-11e7-8867-09fe1b2e227d.png) | ![screenshot from 2017-05-19 22-31-11](https://cloud.githubusercontent.com/assets/1420189/26265817/e61cae32-3ce2-11e7-8d27-d6dd1fa584f4.png)
| 
![screenshot from 2017-05-19 22-29-51](https://cloud.githubusercontent.com/assets/1420189/26265836/02e92374-3ce3-11e7-8190-d109b97e0bab.png) | ![screenshot from 2017-05-19 22-33-45](https://cloud.githubusercontent.com/assets/1420189/26265889/426e212a-3ce3-11e7-962e-c26f10805a78.png) | ![screenshot from 2017-05-20 13-17-07](https://cloud.githubusercontent.com/assets/1420189/26275356/e27b0ffe-3d5e-11e7-8023-f6fe10020ff1.png)
| 
![screenshot from 2017-05-20 15-31-58](https://cloud.githubusercontent.com/assets/1420189/26276148/bb7ac5bc-3d71-11e7-9e21-2dd5a0dee006.png) | ![screenshot from 2017-05-21 11-12-53](https://cloud.githubusercontent.com/assets/1420189/26282695/8b328246-3e16-11e7-8c78-70ed67929a19.png) | ![screenshot from 2017-05-21 12-31-54](https://cloud.githubusercontent.com/assets/1420189/26283102/84def2de-3e21-11e7-9523-f8ae1d400cc5.png)

| 

### Sources
* [List of languages by number of native speakers](https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers#/media/File:Languages_with_at_least_50_million_first-language_speakers.png)
![languages_with_at_least_50_million_first-language_speakers](https://cloud.githubusercontent.com/assets/1420189/26266397/6204357c-3ce5-11e7-82f0-90901badc183.png)

#19

**Comment by hugolpz** [comment]
Seems the Indians are quite active in the opendata for language's field.

See also #19
