### ISSUE TITLE
On click "Download all records by one locuteur" functionality

### ISSUE THREAD

**Issue by hugolpz** [wikimedia-france/Lingua-Libre#2]
Provide the possibility to download a whole serie, as a zip file.

**Core usecase, serving the user:** Most institutions want to run a week long sprint on the system, produce +1000-5000 audios which will be under opensource license per LinguaLibre's terms of uses, download their +1000 files copies, and leave for ever. 

**As of now, serving Wikimedia:** We ask people (speakers, institutions) to contribute their times and send a mass of records to our Wikimedia platform, _without allowing them to get their work back to them_. I currently <u>CANNOT</u> contact l'INALCO or other actors with such a bad deal for them. They will <u>NOT</u> contribute solely for Wikimedia's and Commons.wikimedia.org's interest. LinguaLibre must serve them first, Wikimedia being served as a  byproduct thus creating a win-win for the public. It would be good for the Opensource to have this functionality and usecase posibility asap.

**Comment by hugolpz** [comment]
@zmoostik @0x010C : Salut l'équipe. Who could edit the system so we get this core functionality ?

**Comment by hugolpz** [comment]
@wiese : please review this issue. This "Download serie of audios via single click" is something that important Institutional partners ask us, as a MUST HAVE.
The INALCO is a national institute teaching 105 non-western languages. They are non interested into wikimedia commons. They are interested into getting immediate return on investment, namely : Go into a recording sprint, live with 3000 audio files, so they can show off to their colleagues and research agencies.
You asked me "What contribution will matters ?"
This one will !

**Comment by hugolpz** [comment]
@zmoostik : shall we close this issue ? :dancer:

**Comment by kamomil** [comment]
why close it?

**Comment by hugolpz** [comment]
@kamomil: @zmoostik added the functionality on monday, just before the July 3rd official launch announcement, which went well. You must do a git pull to get it :)
See [commits](https://github.com/wikimedia-france/Lingua-Libre/commits/master)
