### ISSUE TITLE
Can not install in ubuntu 16.04

### ISSUE THREAD

**Issue by tshrinivasan** [wikimedia-france/Lingua-Libre#21]
Getting the following error.

➜  Lingua-Libre git:(master) ✗ composer install    
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets
Could not open input file: bin/console
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets handling the post-install-cmd event terminated with an exception

                                                                                                     
  [RuntimeException]                                                                                 
  An error occurred when executing the "'assets:install --symlink --relative '\''web'\'''" command:  
  Could not open input file: bin/console                                                             
                                                                                                     

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

PHP version is 5.2
composer 1.2

Need help on installing this.

**Comment by hugolpz** [comment]
@tshrinivasan : Did you solve this issue ? How ?
Close issue if it's ok :D

**Comment by wiese** [comment]
@tshrinivasan Please use the docker environment which is now available in the main line.
