### ISSUE TITLE
When changing the language, change the default list of words

### ISSUE THREAD

**Issue by kamomil** [wikimedia-france/Lingua-Libre#27]
Currently when the language is changed in the language selection of a user , the list of words is not changed, we probably want to save a list of words per user per language

### Requirements :

- Input
  - {iso-639-3}-list.txt file with 5k words or items.
- Result
  - when your studio / speaker is set to record {iso-639-3} language, load {iso-639-3}-list.txt
  - (or part of it)

### Alternative
Maintain a static html page with curated lists, which the user download then copy then paste into the text area. 

See also : #39

**Comment by wiese** [comment]
Maybe the default word list should be saved with the language (Database), configurable by the administrator?

**Comment by hugolpz** [comment]
This is related to the corpus linguistic research. See #4 .

**Comment by hugolpz** [comment]
This is dependant on corpus linguistic researches for each languages.
See #4 , by @hugolpz as of now.
I can handle the research side for a dozen of languages. Like, provide 5000k first works (again, see #4).
**We need someone for the tech side !!**
Please volunteer yourself if you can do & have time to.
