### ISSUE TITLE
Replace Javascript build tool

### ISSUE THREAD

**Issue by wiese** [wikimedia-france/Lingua-Libre#28]
Replace `make` used as a build tool for Javascript by something more portable and modern, e.g. [grunt](https://gruntjs.com/).

see `web/js/Makefile`

**Comment by hugolpz** [comment]
I would recommend to keep make.
Grunt is already getting replaced by other systems.
Make is more stable.
@wiese : @zmoostik (Nicolas, main dev) seems neutral on this point.

**Comment by felixknds** [comment]
Aside from just changing to another building tool, what tools from NPM could be interesting here except those for JS minification?
