### ISSUE TITLE
Document denoising processes

### ISSUE THREAD

**Issue by hugolpz** [wikimedia-france/Lingua-Libre#29]

**Comment by hugolpz** [comment]
- **See [Wiki's tutorials](../wiki/Tutorials)**

**Comment by Nudin** [comment]
I would really like this feature! We have a lot of really noisy files on commons and denoising makes them so much better.

A nice alternative to SoX would be [RNNoise](https://people.xiph.org/~jm/demo/rnnoise/). Pretty new but does not need to be trained with a silent part.

**Comment by hugolpz** [comment]
Hi Nudin,
Note that this issue is for documenting the denoising process, which have been done on the repository's wiki.

We have conflicting positions on adding denoising to LinguaLibre as it alters the original audio. No plan to add it so far.

Out of curiosity, we will look into RNNoise. If you master it, feel free to share / add a minimalist tutorial to the wiki.
