### ISSUE TITLE
Chromium Error "Impossible d’accèder à l’interface audio"

### ISSUE THREAD

**Issue by hugolpz** [wikimedia-france/Lingua-Libre#3]
> Impossible d’accèder à l’interface audio ! Peut-être n’avez-vous pas branché de microphone…

Je ne peux enregistrer sur mon PC.

![screenshot from 2017-02-23 12-49-23](https://cloud.githubusercontent.com/assets/1420189/23258022/a388d47e-f9c6-11e6-9ac7-cfdc4089bf98.png)

### Materiel
> Chromium, version 55.0.2883.87 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

![screenshot from 2017-02-23 12-51-57](https://cloud.githubusercontent.com/assets/1420189/23258092/f2e8027e-f9c6-11e6-932b-f01249506532.png)

### Sound settings
Le micro fonctionne : j'entends bien ma voie dans le casque, et ca vient bien du bon microphone.

![screenshot from 2017-02-23 12-53-13](https://cloud.githubusercontent.com/assets/1420189/23258132/175c5812-f9c7-11e6-8300-ad1b1d394fee.png)
![screenshot from 2017-02-23 12-53-28](https://cloud.githubusercontent.com/assets/1420189/23258159/35e0a860-f9c7-11e6-8bec-180969bdfb08.png)

**Comment by hugolpz** [comment]
Workaround: Move to Firefox.

> 

![firefox_mic_autorisation0](https://cloud.githubusercontent.com/assets/1420189/23259085/ab8bdcde-f9cb-11e6-8c0d-252468e10a96.png)
![firefox_mic_autorisation1](https://cloud.githubusercontent.com/assets/1420189/23259084/ab8b8b08-f9cb-11e6-83ce-f618d43a60a0.png)
![firefox_mic_autorisation2](https://cloud.githubusercontent.com/assets/1420189/23259086/ab8c55e2-f9cb-11e6-9cb3-1c086f3722d2.png)

**Comment by 0x010C** [comment]
@hugolpz Je vais m'en occuper lundi, mais avant de mettre en place un certificat, on va migrer le serveur web d'apache2 vers nginx.

**Comment by 0x010C** [comment]
:white_check_mark: Migration sur nginx
:white_check_mark: Mise en place du certificat
:white_check_mark: Redirection http -> https

**Comment by hugolpz** [comment]
Have you been successful to record on chromium ?
Was someone successful ?
I made quick a test but failed.
May need to restart computer.
