### ISSUE TITLE
Add possibility of OAuth login via Wikipedia account system 

### ISSUE THREAD

**Issue by hugolpz** [wikimedia-france/Lingua-Libre#31]
Issue made to keep idea in mind.

Use-case : 
- user login on lingualibre
  - if username DOES NOT exist on Wikipedia, create Wikipedia account, then LOG IN globally
  - if username EXIST on Wikipedia, require same password as Wikipedia and LOG IN globally
  - if username EXIST on Wikipedia and PASS FAILS, then display : _"This username seems already taken with another password. Please check your username, password, or use an other username to log in"_. This then fall back on the 2 previous paths. :dancer: 

See also : [OAuth](https://en.wikipedia.org/wiki/OAuth), [Help:OAuth](https://www.mediawiki.org/wiki/Help:OAuth)

**Comment by tshrinivasan** [comment]
We need this feature to be implemented in lingua libre, so that we can use the user's wikipedia account to upload the files to commons and link to dictionary.

**Comment by hugolpz** [comment]
French devs would prefer that each user on LinguaLibre push to commons via its own Wikimedia account.
@0x010C : any forcast for you setting this up ? Can you ask your boss some time to work on this ?

**Comment by tshrinivasan** [comment]
Discussed this on the mailing list for commons[1].
Please read this thread.
Commons devs apparently prefer oauth only.
[1]: https://lists.wikimedia.org/pipermail/commons-l/2017-May/007861.html

**Comment by hugolpz** [comment]
Yes yes, push to commons via OAUTH... 

My username on LL is `yug` <u>or whatever</u>, I provide my wikipedian username as  `yug`, 
So by connecting on LL, when I records an audio there, then at LL's pipeline sends the audios to commons...
...on commons, the file's history must show up `User:Yug`, something such : 

!["Give my copyright back!", told the Iron Lady](https://cloud.githubusercontent.com/assets/1420189/26683814/6300a50a-46e5-11e7-875e-6d7e4d10d054.png)

NOT user:LinguaLibreBot or similar, which would be copyright thief by bot ! ^^

**Comment by hugolpz** [comment]
Federico Leva (Nemo:
> Nowadays, tools generally use OAuth to upload on the user's behalf. See 
> examples:
> https://commons.wikimedia.org/wiki/Commons:Upload_tools#Transfer_tools
> 
> Examples:
> https://www.mediawiki.org/wiki/OAuth/For_Developers
> https://github.com/toollabs/video2commons/blob/master/video2commons/frontend/app.py#L121
> https://github.com/wikisource/ia-upload/blob/master/src/IaUpload/OAuth/MediaWikiOAuth.php
