### ISSUE TITLE
Directory structure to store all the audio files

### ISSUE THREAD

**Issue by tshrinivasan** [wikimedia-france/Lingua-Libre#38]
**Currently**, all the audio files are stored in a single directory.
On a production environment, we will create huge number of files, which will lead to 'large number of files in a single directory" issue.

**We need a scalable directory structure.**
Make multiple directories with sessionid name or timestamp, and place the audio files inside them.

**Comment by hugolpz** [comment]
By language should be good as of now. 
But English or French could quickly become quite overloaded indeed as each wikipedian records his great mother :dancer: .
