### ISSUE TITLE
Get OAuth autorization from Wikimedia MediaWiki's devs

### ISSUE THREAD

**Issue by hugolpz** [wikimedia-france/Lingua-Libre#42]
Get the authorisation.

 ----

**EDIT:** [We got the authorization on Meta , see on meta](https://meta.wikimedia.org/wiki/Special:OAuthListConsumers/view/1eee51d3553ee71cb165d77e14650421)

**Comment by xenophon75** [comment]
We got the authorization on Meta : https://meta.wikimedia.org/wiki/Special:OAuthListConsumers/view/1eee51d3553ee71cb165d77e14650421
