### ISSUE TITLE
Relationship with Commons needs to be clearly defined

### ISSUE THREAD

**Issue by felixknds** [wikimedia-france/Lingua-Libre#47]
My understanding is that the plan is to use Commons as a repository (see #33 #36) to host the files (once we have got the #31 issue solved). However, some things need to be determined first:
- Once Commons can readily be used for hosting the files, will they still be (also) hosted on Lingua Libre?
- How to allow the user to retract before sending the files to Commons (for example to delete a test or a bad recording)? For the record, once they have been uploaded to Commons, they can no longer be deleted (from Commons), at least not in a systematic fashion.
- What happens then with the "Delete" functionalities of Lingua Libre?

The whole process needs to be determined clearly before it can be envisaged to use Commons as a file repository.

**Comment by hugolpz** [comment]
@0x010C : can we close this with a little note on the fresh implementation-policy ?
