### ISSUE TITLE
List of languages to import into Lingua Libre

### ISSUE THREAD

**Issue by xenophon75** [wikimedia-france/Lingua-Libre#48]
### To do
- [ ] Find suitable base list for devs. [Under review]
- [ ] List missing French dialects @Lyokoi
- [ ] Add list to the lingua-libresystem
- [ ] Add autocompletion filter
- [ ] Add missing French dialects

### Candidate base lists
- [List of ISO 639-3 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-3_codes)  (7848 langues, English) :
  -  Download list : SIL.org > [ISO 639-3 Downloads](http://www-01.sil.org/iso639-3/download.asp) > [UTF-8: iso-639-3_Code_Tables_20170217.zip](http://www-01.sil.org/iso639-3/iso-639-3_Code_Tables_20170217.zip)
   - Convention for addons : [List of ISO 639-3 language codes used locally by Linguist List](https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Languages/List_of_ISO_639-3_language_codes_used_locally_by_Linguist_List)
- Wiktionary (5579 languages, French) :
  - https://fr.wiktionary.org/wiki/Wiktionnaire:Liste_des_langues and its [.tsv.txt](https://github.com/wikimedia-france/Lingua-Libre/files/1161445/Liste.des.langues.du.WIktionnaire.tsv.txt)
  - [Liste des langues du WIktionnaire.txt](https://github.com/wikimedia-france/Lingua-Libre/files/1082993/Liste.des.langues.du.WIktionnaire.txt)
- Max Planck Institute > Glottolog.org (18976 dialects, English) : 
  - [Download page](http://glottolog.org/meta/downloads)

### Complementary tools
- [Unicode CLDR Project](http://cldr.unicode.org/index) (617 French)
  - [labels](https://github.com/unicode-cldr/cldr-localenames-full/tree/master/main) > [FR](https://github.com/unicode-cldr/cldr-localenames-full/blob/master/main/fr/languages.json)

### Sample view

**UTF-8: iso-639-3_Code_Tables_20170217.zip** : 
![screenshot from 2017-07-17 17-11-00](https://user-images.githubusercontent.com/1420189/28275139-4737c4e6-6b13-11e7-9f0c-c7f1171dac7b.png)

**Wiktionaire > Liste.des.langues.du.WIktionnaire.tsv.txt**
![screenshot from 2017-07-20 09-11-06](https://user-images.githubusercontent.com/1420189/28404929-880a6c16-6d2b-11e7-8400-07c63702010f.png)

**Glottolog.org > languages-and-dialects-geo.csv**
![screenshot from 2017-07-20 00-30-03](https://user-images.githubusercontent.com/1420189/28392541-a92468a0-6ce2-11e7-8f43-587741378f3e.png)

### Candidate filtering systems
Feel free to open a new issue on this.
- [JS/JSON Select2.js](https://select2.github.io/examples.html)

![xkcd_standards](https://user-images.githubusercontent.com/1420189/28528793-0762c812-708f-11e7-8f43-f6cb03192b9e.png)

**Comment by hugolpz** [comment]
@zmoostik j'ai trouvé **le fichier source de l'ISO 639-3 codes**. Cf plus haut. Le code iso-639, le code ISO-639-2, et le nom de la langue en anglais sont présents. All good.

Pour les dialectes francais **manquants**, suivre la recommendation de "List of ISO 639-3 language codes used locally by Linguist List" serait une bonne pratique. Cf plus haut.

Pour **l'ajout de langues sur mesure**, l'outils UI d'administration, associé à un cours paragraphe explicatif, sera utile. Une convention de nommage pour "pseudo-ISO-639-3 codes" doit être présente.

Pour **la selection de la langue**, un input or select element avec auto-complétion serait bien, voir select2.js. Il est connu pour [tenir la charge](https://stackoverflow.com/questions/15041058/select2-performance-for-large-set-of-items) au moins jusqu'à 2000 elements.

**Comment by pamputt** [comment]
Il est aussi possible d'obtenir une liste des langues depuis une requête Wikidata
* Cette [requête ](http://tinyurl.com/y9n9uwqu) donne une liste de toutes les langues avec un nom en français (3658 résultats)
* Cette [requête ](http://tinyurl.com/ycsq8sm3) ajoute les dialectes à la liste des résultats (4116 résultats)
* Cette [requête ](http://tinyurl.com/y8fbxzoj) donne la liste de toutes les langues et dialectes, qu'ils aient ou non une traduction en français (~10600 résultats)
Je travaille actuellement sur les langues sur Wikidata afin d'avoir une base de données propres, structurées et utilisable mais ça va prendre du temps. Bref, on peut déjà utiliser ce qui est présent en l'état même si c'est perfectible.
