### ISSUE TITLE
FatalErrorException in AppExtention.php 0

### ISSUE THREAD

**Issue by Lyokoi** [wikimedia-france/Lingua-Libre#49]
Hi there !
I git cloned and try to run the Vienna version of LinguaLibre. On `localhost/app_dev.php` I got this error : 

![screenshot from 2017-06-18 16-24-17](https://user-images.githubusercontent.com/1420189/27261398-9a21457a-5442-11e7-876d-fa39d834f873.png)

Any idea ?

**Comment by wiese** [comment]
Hi,

what you experience is a problem of dependency management, namely the lack of a [composer.lock file](https://blog.engineyard.com/2014/composer-its-all-about-the-lock-file) - which leaves you with a twig version that is incompatible with AppBundle's AppExtension implementation. 
I can only speculate as to both, the version you have now installed, and the "correct" version which the application is meant to use. 
However, the error message indicates that you do have verison 1 of twig installed (`getName` was deprecated in 1.26 and removed in 2.0), try switching to version 2 and see if the error disappears.

You discovered a general problem (not one introduced during Vienna) and if you manage to configure your application in a satisfying way it would benefit the project if you submit the resulting composer.lock file as a PR.

Cheers

**Comment by hugolpz** [comment]
@Lyokoi : Did  Wiese's answer solved your issue ? Can we close it ?
