### ISSUE TITLE
Download a category from commons to document on the wiki

### ISSUE THREAD

**Issue by Lyokoi** [wikimedia-france/Lingua-Libre#50]
When link between LL and Commons will be ok, we need to explain to users (linguists especially) to use Imker ( https://commons.wikimedia.org/wiki/Commons:Imker_(batch_download) ) to download an entire category of sounds.

**Comment by hugolpz** [comment]
See [**How to download all files from one Commons category via Imker?**](../wiki/Download-Commons-category)
