### ISSUE TITLE
Create API manual for swac-recorder.js lib

### ISSUE THREAD

**Issue by hugolpz** [wikimedia-france/Lingua-Libre#52]
Write a readable README.md swac-recorder.js.

For source codes, see [/js/swac-recorder](https://github.com/wikimedia-france/Lingua-Libre/tree/master/web/js/swac-recorder).

For example of README.md API, see [Howler.js](https://github.com/goldfire/howler.js/)

**Comment by 0x010C** [comment]
Blocked by #71

**Comment by hugolpz** [comment]
Closed. See https://github.com/lingua-libre/LinguaRecorder's readme.
