### ISSUE TITLE
Hi, How do I access the database?

### ISSUE THREAD

**Issue by kamomil** [wikimedia-france/Lingua-Libre#53]
I get:

dafna@guri:~/wiki/Lingua-Libre$ sudo mysql -u lingualibre --password=bienvenue
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'lingualibre'@'localhost' (using password: YES)

**Comment by wiese** [comment]
Hi @kamomil,

if you use [the docker-compose set-up](https://docs.docker.com/compose/reference/), then the database resides within a dedicated container on which you have to run database-specific commands.
Assuming you have docker-compose running (`docker-compose up -d`), run
`docker-compose exec database mysql -u lingualibre --password=bienvenue` to replicate what you did.

Explanation:
* `docker-compose` - the docker-compose binary
  * `exec` - the docker-compose command
    * `database` - the name of the service to execute (compare docker-compose.yml keys)
      *  `...` - the binary to run / any command

**Comment by hugolpz** [comment]
@kamomil : is it ok ? can we close this issue ?

**Comment by kamomil** [comment]
Hi, yes, can close
