### ISSUE TITLE
Right-to-left abusive required="required" property-value makes it wrongly compulsory

### ISSUE THREAD

**Issue by hugolpz** [wikimedia-france/Lingua-Libre#63]
When creating a new language, the html form forced me to check "right-to-left" as true. 

![screenshot from 2017-08-10 14-52-59](https://user-images.githubusercontent.com/1420189/29187369-7be915fa-7ddd-11e7-8033-8844f804273a.png)

Can someone make a fix ?

**Comment by hugolpz** [comment]
I think the bug comes from [there](https://github.com/wikimedia-france/Lingua-Libre/blob/e97a4b2669cb14e95652c18771834d7d9a80b616/src/AppBundle/Controller/LanguagesController.php#L43-L44).

![screenshot from 2017-08-10 19-49-01](https://user-images.githubusercontent.com/1420189/29196829-0da13b36-7e05-11e7-9d6e-8f1073eae7c4.png)

```
	->add('description', TextareaType::class, array("required" => false))
	->add('isRtl', CheckboxType::class)
```

Which we need to replace by : 

```
	->add('description', TextareaType::class, array("required" => false))
	->add('isRtl', CheckboxType::class, array("required" => false))
```

**Comment by kamomil** [comment]
Hi, Ill check it.
I think the correct  solution for that is actually to remove this checkbox and have a map between each language to direction.

**Comment by kamomil** [comment]
Hi,
So your suggestion works ok, shall I push it?

**Comment by hugolpz** [comment]
I don't do php, i just inspected the html code and made logical deduction to find the needle in the github-hosted php code. It needs to be tested in dev mode by someone (you?) then pushed live on website by Nicolas.

**Comment by hugolpz** [comment]
@kamomil : I just saw your edit and push, thanks you :D
I send the new to @zmoostik so this fix is deployed. :+1:

**Comment by kamomil** [comment]
cool :)
