### ISSUE TITLE
Unable to run on a MacOS

### ISSUE THREAD

**Issue by psubhashish** [wikimedia-france/Lingua-Libre#7]
Hi, I tried to follow the steps, downloaded all the software mentioned in the prerequisite section and tried to run the code but it did not work for me. Can you please help? I have copied the command from the terminal [here](https://codeshare.io/Gk0lKM). A screenshot of the final code run is below:
<img width="564" alt="Screenshot of the command" src="https://cloud.githubusercontent.com/assets/1258090/25063130/b2429bf2-21f9-11e7-9dd2-e0496517b983.png">

**Comment by psubhashish** [comment]
I also tried again. This time @gyan111 of @OdiaWikimedia helped from the start to the end. but there is some other complication and we couldn't successfully make it work though we succeeded in installing Composer. Sharing the output below:
<img width="1440" alt="screen shot 2017-04-16 at 12 37 55 pm" src="https://cloud.githubusercontent.com/assets/1258090/25069597/83d646f6-22a3-11e7-80bb-cc27267f61fa.png">
<img width="1440" alt="screen shot 2017-04-16 at 12 44 34 pm" src="https://cloud.githubusercontent.com/assets/1258090/25069598/8c798c00-22a3-11e7-9019-20ce3f25869b.png">

**Comment by hugolpz** [comment]
See https://github.com/hugolpz/SWAC_recorder/issues/6
If your aim is to records audios, no need to reinstall LinguaLibre (a web platform).
You rather need to sign up and use it online.

**Comment by psubhashish** [comment]
Thanks for clarifying. Closing this issue in that case.
