### ISSUE TITLE
Split the swac-recorder into an independant library

### ISSUE THREAD

**Issue by 0x010C** [wikimedia-france/Lingua-Libre#71]
The swac-recorder and the recording studio's interface are completely merged one into the other.

It would be much better to separate the view of the recorder, in terms of code clarity, performance, possibility of improvement and reuse.

**Comment by hugolpz** [comment]
@0x010C , did you tackled this ? Any js revamp available ?

**Comment by 0x010C** [comment]
I've just finished the complete rewrite of the recorder, and splitted it into a new repository: https://github.com/0x010C/LinguaRecorder
