### ISSUE TITLE
php zip extension not installed

### ISSUE THREAD

**Issue by kamomil** [wikimedia-france/Lingua-Libre#74]
Hi,
I just installed the site  [here](http://35.225.154.88:8000) and started to translate it.

Then when clicked "download" (Télécharger) to download my recordings, I got a server error:

> Fatal error: Class 'ZipArchive' not found in /code/src/AppBundle/Controller/SoundsController.php on line 209

I was able to fix it by replacing the line 

`RUN apt-get update  && docker-php-ext-install -j$(nproc) pdo pdo_mysql`

with the line 

`RUN apt-get update && apt-get install -y zlib1g-dev && docker-php-ext-install -j$(nproc) pdo pdo_mysql zip`

In the file **docker/app//Dockerfile**

pushed it to [my fork](https://github.com/kamomil/Lingua-Libre/commit/c884440582fc45cbd130b1ca5dfd51a0c03538f0)

**Comment by hugolpz** [comment]
Feel free to push to this repository. I noticed the devs of your current edits.
