### ISSUE TITLE
Switch export format from ogg to mp3

### ISSUE THREAD

**Issue by kaldari** [wikimedia-france/Lingua-Libre#77]
All the mp3 patents have expired and mp3 is now the preferred audio format for Commons since it's natively supported on far more devices (especially mobile devices).

**Comment by hugolpz** [comment]
So far and if I remember correctly :
1. We do and continue to plan to export .flac files, as they have : 
   - built-in support for metadata 
   - have correct/solid browser support as of 2018
   - are supported by howlerjs : "mp3", "mpeg", "opus", "ogg", "oga", "wav", "aac", "caf", m4a", "mp4", "weba", "webm", "dolby", "flac".
2. Commons has built-in conversion system to alternative formats
3. We also provide conversion and web integration tutorials.

Wikimedia-france/Lingua-Libre > [/wiki/Tutorials](../wiki/Tutorials) :
- [x] [How to convert batch of audio files into mp3 ?](../wiki/Convert_audios?) (or other)
- [x] [How to play in webpages ?](../wiki/Inpage) See [howlerjs.com](https://howlerjs.com) & [doc]

**Comment by hugolpz** [comment]
Ping @

**Comment by kaldari** [comment]
@hugolpz: I'm glad to hear that Lingua Libre is using flac, although I'm a bit confused. The code looks like it exports to ogg, not flac: [/src/AppBundle/Controller/ExportController.php](https://github.com/wikimedia-france/Lingua-Libre/blob/c38e54283ca7785fd2728e428afff236e0a03801/src/AppBundle/Controller/ExportController.php).

I'm not familiar with the code, though, so maybe I'm looking in the wrong place.

**Comment by Nudin** [comment]
@kaldari I think this is a misunderstanding. You mean Ogg Vorbis when you say 'ogg', but ogg is the container format that can contain Ogg Vorbis or Flac audio-content. Flac does not has an own container format. (It was developed by the same peoples who did Vorbis). You can name ogg-files containing flac-audio ether .ogg or .flac – thats no difference except for the human to more easily distinguish. The file you linked does only the filenaming and uses .ogg – so that's ok. (But one could discuss if .flac would be better).

**Comment by hugolpz** [comment]
> Disclaimer : I'am mainly community manager on this project.

@kaldari : 
**LL-PHP:** Oh, indeed. From memory the current code based on PHP and JS works with flac, with a duplicata in ogg if I remember well. Flac for loose-less quality and metadata. Ogg for convenience (filesize). LL-PHP is going to be phased out in May (likely).

**LL-Wikibase+JS:** The [coming revamp](https://meta.wikimedia.org/wiki/Grants:Project/0x010C/LinguaLibre) (production TBA in May, at the Barcelona Hackaton ?), is JS and Wikibase-based and is expected to be plugged onto Commons via API and Oauth. There, according to recent meetings, we plan to work with flac, letting Commons background processes handle the conversion to mp3, ogg and few other format I believe.

@Nudin : Oh, thanks for the expertise :+1:
